### ISSUE TITLE
[1.18]在遊戲中加載資源包後，手冊翻譯需要退出重進世界才會應用

### ISSUE THREAD

**Issue by StarskyXIII** [kappa-maintainer/PRP#1]
卸載資源包也是同樣情況，翻譯會還在，退出世界重進後才會變回原文。

**Comment by kappa-maintainer** [comment]
哪个模组，用的什么资源包？

**Comment by StarskyXIII** [comment]
我拿 Apotheosis 模組進行測試，並使用 RPMTW 的漢化資源包。
[RPMTW-1.18.zip](https://github.com/kappa-maintainer/PRP/files/8820298/RPMTW-1.18.zip)

**Comment by kappa-maintainer** [comment]
[prp.zip](https://github.com/kappa-maintainer/PRP/files/8822510/prp.zip)
试试这个

**Comment by StarskyXIII** [comment]
感謝，已修復。
順便想請問有製作 Fabric 版本的計畫嗎？
Fabric 1.18 上還沒有模組實現相同的功能。
RPMTW 的這個功能目前也是壞掉的狀態。

**Comment by kappa-maintainer** [comment]
没有，因为这个模组完全是出于个人需要做的
其原理并不复杂，完全可以自行移植

**Comment by StarskyXIII** [comment]
好的，謝謝你
