### ISSUE TITLE
進入世界時，會導致客戶端短暫凍結

### ISSUE THREAD

**Issue by StarskyXIII** [kappa-maintainer/PRP#2]
測試模組包：FTB StoneBlock v1.6.1
PRP 版本：1.0.5
遊戲版本：1.18.2

遊戲日誌：https://mclo.gs/dzhi4D2

調試日誌：https://mclo.gs/koofxOA
（日誌直接拉到最下面看）

問題描述：創建世界並進入地圖後，遊戲畫面剛出現時，客戶端會凍結大約一分多鐘，
直到日誌跳出 Patchouli 的錯誤訊息後，才能正常行動。

**Comment by kappa-maintainer** [comment]
推测为汉化包含有错误或版本落后
请移除报错的几个手册（rftools、thermal）后再观察有无类似现象

**Comment by StarskyXIII** [comment]
同樣問題仍然會發生在，遊戲語言為英文，且未安裝任何漢化包的情況。

遊戲日誌：https://mclo.gs/ZnqLuhi

調試日誌：https://mclo.gs/jeN6e8u

**Comment by kappa-maintainer** [comment]
由于模组众多，debug困难，目前建议先使用RPMTW代替
不过据我所知1.18下除了神化已经没用多少需要prp的模组，能问下为什么要装吗

**Comment by StarskyXIII** [comment]
就我所知，RPMTW 1.3.2 for 1.18.2，使用的是您 PRP 1.16.5 的代碼。
至於 RPMTW 1.4.3，則是使用您 PRP 1.18.2 的代碼。
前者的實現是過時不再可用的。後者則是有相同的問題。

其實還有許多模組仍有著 patchouli 在 data 而無法被資源包覆蓋的問題，
除了 Apotheosis 以外，還有像是：LaserIO、Industrial Foregoing、Thermal Series、Allthemodium。

至於客戶端凍結問題，經本人測試，
在搭配另一款 ModernFix 1.18.2 建置版使用後，
凍結問題似乎就神奇地解決了。
但目前該模組 1.18.2 版本，尚在 Discord 內部測試，
故暫時不兼容 ATM7-To the Sky 模組包。

早前我曾經測試過模組包 Caveopolis，其 v4.1 時還未有凍結問題，
但在 v4.2 將所有模組更新到最新版本，
且安裝 PRP 後，也有相同的凍結問題了
Caveopolis 算是一款輕量的模組包，
希望能夠幫助你縮小 Debug 範圍

**Comment by kappa-maintainer** [comment]
最近有点忙，能不能试下1.0.4版本？我怀疑是支持热重载做的改动导致的

**Comment by kappa-maintainer** [comment]
经测试1.0.4不会冻结，切换即可
考虑到1.0.5只加了热重载功能，mixin复杂到我发成beta版本，就不专门去修了
mcmod上最近出了一个跨平台版，以后可能那边会比我更新快
